### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by jbarish** [Diamondshell/CS546Final#13]
When the user types in the search bar, the website should re-route itself to the browse page.
A request then needs to be sent to the server.
The server needs to strip out any bad characters, and respond with a json of all applicable recipes (in abbreviated form)
The website should then display all recieved recipes to the user.

**Comment by ghost** [comment]
Implemented getRecipesByLikeName, should find similar names.

**Comment by jbarish** [comment]
Done
