### ISSUE TITLE
Random Recipe

### ISSUE THREAD

**Issue by jbarish** [Diamondshell/CS546Final#16]
When the user clicks random recipe, they are presented with filters.
The user will click any filters, and then a post is sent to the server.
The server should redirect the page to recipe/ID_of_random_recipe

**Comment by ghost** [comment]
Made `getRandomRecipe`, if you guys want to make a route for it, should be easy to do. Receives a (potentially null) filter, just like `getRecipesByFilter`

**Comment by mtknapp** [comment]
Complete
