### ISSUE TITLE
Save to Favorites

### ISSUE THREAD

**Issue by jbarish** [Diamondshell/CS546Final#17]
When the user clicks save to favorites, 
a request should be sent to the server. The server should add the recipe to the users favorites, and respond with some sort of ok message.
On reciept of ok, the recipe page should change "save to favorites" to "saved to favorites"

**Comment by mtknapp** [comment]
Saves to favorites, does not currently change to "saved to favorites"

**Comment by mtknapp** [comment]
Completed.
