### ISSUE TITLE
Deleting Recipe

### ISSUE THREAD

**Issue by jbarish** [Diamondshell/CS546Final#24]
When deleting a recipe from existence, the website needs to send delete request, server needs to delete recipe, and reply to user. User page should re-render to show removal.

Currently clicking delete shows edit page (bug)

**Comment by zachhackett** [comment]
Bug aspect fixed. Delete button no longer shows edit modal (though delete functionality is not implemented as of yet).

**Comment by mtknapp** [comment]
Completed.
